version: '3.4'


services:
  nas-cloud:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    entrypoint: ["java",
                 "-Xms512M","-Xmx2048M","-jar",
                 "/app/nas_cloud.jar",
                 "-Dfile.encoding=UTF-8",
                 "--spring.profiles.active=prod"]
    environment:
       TZ: 'Asia/Shanghai'
       server.port: 9001
    ports:
      - "9001:9001"
    network_mode: "host"

